openapi: 3.0.0
info:
  title: Bedrock APIs
  version: 1.0.0

servers:
  - url: http://localhost:8080
  - url: https://bedrock-henna.vercel.app

paths:
  /auth/signup:
    $ref: './routes/auth/signup.yaml'

components:
  schemas:
    signupRequest:
      $ref: './components/schemas/auth/signupRequest.yaml'
