openapi: 3.0.0
info:
  title: Bedrock APIs
  version: 1.0.0

servers:
  - url: http://localhost:8080
  - url: https://bedrock-henna.vercel.app

paths:
  /auth/signup:
    $ref: './routes/auth/signup.yaml'
  # /auth/login:
  #   $ref: './routes/auth/login.yaml'
  # /auth/logout:
  #   $ref: './routes/auth/logout.yaml'
  # /auth/csrf-token:
  #   $ref: './routes/auth/csrfToken.yaml'

  # /vaults:
  #   $ref: './routes/vaults.yaml'

components:
  schemas:
    signupRequest:
      $ref: './components/parameters.yaml'
  # parameters:
  #   $ref: './components/parameters.yaml'
  # securitySchemes:
  #   $ref: './components/security.yaml'
